# Generated by Django 4.2.5 on 2023-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clgapp", "0003_alter_student_materials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=1),
        ),
    ]
